### ISSUE TITLE
serverspec tests failing

### ISSUE THREAD

**Issue by goutham27** [jvoorhis/vagrant-serverspec#25]
Failures:

  1) File "/opt/tomcat7" should be directory
     On host `127.0.0.1'
     Failure/Error: it { should be_directory}
     SystemStackError:
       stack level too deep

     # C:/Users/user/.vagrant.d/gems/gems/specinfra-2.59.6/lib/specinfra/properties.rb:10:in `properties'
     # C:/Users/user/.vagrant.d/gems/gems/specinfra-2.59.6/lib/specinfra/helper/properties.rb:7:in `property'
     # C:/Users/user/.vagrant.d/gems/gems/specinfra-2.59.6/lib/specinfra/helper/os.rb:7:in `os'
    # C:/Users/user/.vagrant.d/gems/gems/specinfra-2.59.6/lib/specinfra/configuration.rb:38:in `os'
     # C:/Users/user/.vagrant.d/gems/gems/specinfra-2.59.6/lib/specinfra/helper/os.rb:16:in `detect_os'      # C:/Users/user/.vagrant.d/gems/gems/specinfra-2.59.6/lib/specinfra/helper/os.rb:9:in `os'
     # C:/Users/user/.vagrant.d/gems/gems/specinfra-2.59.6/lib/specinfra/configuration.rb:38:in `os'
     # C:/Users/user/.vagrant.d/gems/gems/specinfra-2.59.6/lib/specinfra/helper/os.rb:16:in `detect_os'

I tried adding below lines in spec_helper.rb file but still same issue, looks like its unable to detect os..
Is there anythign I am missing?
require 'serverspec'
require 'net/ssh'

set :backend, :ssh

`# Disable sudo`
` set :disable_sudo, true`

`# Set environment variables`
 `set :env, :LANG => 'C', :LC_MESSAGES => 'C'`
`# Set PATH`
` set :path, '/sbin:/usr/local/sbin:$PATH'`

Below is my Gemfile

source 'http://rubygems.org'

puppetversion = ENV.key?('PUPPET_VERSION') ? "#{ENV['PUPPET_VERSION']}" : ['= 4.3.2']
gem 'puppet', puppetversion
gem 'puppetlabs_spec_helper', '1.1.1'
gem 'puppet-lint', '1.1.0'
gem 'serverspec', '2.36.0'
gem 'facter', '2.4.6'
gem 'mocha', '1.1.0'
gem 'hiera', '3.0.6'
gem 'rake',  '10.4.2'
gem 'r10k', '2.3.0'
gem 'winrm', '1.8.1'

platforms :mswin do
  gem "win32console"
end

ruby '2.3.0'

**Comment by goutham27** [comment]
This is the full error log...I have upgrade specinfra to 2.61.1 still no luck
https://gist.githubusercontent.com/goutham27/6a56f18b4c6bb8c56a97e1dbb6c033ec/raw/38dbad99426fc3267846c43bbd73f6bc7862ddd1/serverspecerror.log

**Comment by goutham27** [comment]
found the issue..there was a serverspec plugin under vagrant and it caused the issue..i uninstalled it..it's working now..

```
c:\git>vagrant plugin list
oscar (0.5.1)
serverspec (2.36.0)
vagrant-serverspec (1.1.1)
vagrant-share (1.1.5, system)
```
